### ISSUE TITLE
Type Checking

### ISSUE THREAD

**Issue by akhilmd** [Rahul-RB/PyRust#12]
Alter parsing code and augment AST to handle types correctly. Note the following rules:
- [ ] ~Literal could be out of range for a type. Eg: `256u8`~
- [x] All constants in a binaryOp should be same type as other operand's type.
- [x] Operand of unaryOp - (MINUS) cannot be any unsigned type or char.
- [x] Both operands of binaryOps and its result should be of same type.
- [x] Operands of binaryOp `+`, `-`, `*`, `/`, `%` (PLUS, MINUS, TIMES, DIVIDE, MODULUS) cannot be of type bool or char.
- [ ] ~Results of binaryOps can cause overflow:~
	- [ ] ~Eg: `127i8 + 1i8`, 0u8 - [ ] 1u8, 127i8 * 2i8~
	- [ ] ~Warning is displayed when operands are constants.~
	- [ ] ~When run, program crashes ("panic" in Rust terminology).~
- [x] Operands of unaryOp `!` (LNOT) cannot be of type char or float.
	- [ ] ~Operation done by `!`: `!x = -1 - x`~
- [x] There is no `+` (PLUS) unaryOp.
- [x] Result of `if` and `while`'s conditional expression should be bool only.
- [x] BinaryOps LT, GT, LE, GE, EQ, NE can operate on all types.
- [x] BinaryOps LAND and LOR only operate on bool operands.
- [x] During assignment, LHS type should be same as RHS type.

**Comment by Rahul-RB** [comment]
Logical and and the bitwise and are both same in Rust. How are we handling this?

**Comment by akhilmd** [comment]
Follow [this](/Rahul-RB/PyRust/tree/issue-12) branch.
