### ISSUE TITLE
Add support for else if

### ISSUE THREAD

**Issue by akhilmd** [Rahul-RB/PyRust#19]
This was broken when we changed the production for compound statement from `compStmt : lbrace stmtList rbrace | stmt` to `compStmt : lbrace stmtList rbrace`. Consider fixing this by adding `selStmt : IF expr compStmt ELSE selStmt` to the selStmt production rule.

**Comment by Rahul-RB** [comment]
So `selStmt` will have two productions, one for `IF` and one for `WHILE` ?

**Comment by akhilmd** [comment]
No. `WHILE` has nothing to do with `selStmt`.
