### ISSUE TITLE
Coercions

### ISSUE THREAD

**Issue by akhilmd** [Rahul-RB/PyRust#7]
Implement coercion based on [this](https://rustbyexample.com/types/cast.html). This is probably best if done after basic AST generation is working.

**Comment by akhilmd** [comment]
Closing since Rust does not provide coercion and casting is not a project requirement.

From Rust docs:
> Rust provides **no** implicit type conversion (**coercion**) between primitive types. But, explicit type conversion (**casting**) can be performed using the **`as`** keyword.

**Comment by Rahul-RB** [comment]
Okay, noted. No need for explicit type casting as of now as discussed before.
